name = "worker-typescript-template"
type = "javascript"
zone_id = "6dbd4254f2f1ff9809acc76f94ad6fa1"
account_id = "1c2b97f5ee91f8c89a1459ae81a11e98"
workers_dev = true
compatibility_date = "2020-01-01"
formdata_parser_supports_files = true

kv_namespaces = [
    { binding = "MY_KV", id = "3bd1388bacc141a28a76f77e016422f2" },
    { binding = "TOKENS", id = "f7c4f429dc2a45eb9d826ed8c6029ee5" }
]
[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"


